### ISSUE TITLE
[Enhance] Using TypeScript `paths` to import file

### ISSUE THREAD

**Issue by Nbsaw** [Nbsaw/ruka#28]
says byebye to relative path

**Comment by Nbsaw** [comment]
Seen like not work .. https://github.com/facebook/create-react-app/issues/5645

Hack also not work ...

**Comment by LonelyLiaR** [comment]
look [this](https://nghtmre.surge.sh/#/p/5), scroll down.
it will works and let you say bye bey to relative path.

![](https://i.loli.net/2019/05/10/5cd54f97ad66c.jpg)

**Comment by Nbsaw** [comment]
@LonelyLiaR 我看了你发的那个。二楼贴了链接。 不太想这样搞，就放这了。我想等官方支持。。。
